# Site metadata
title: Mixtape
description: Mixtape is a vaporwave theme for Jekyll sites and GitHub Pages.

# Analytics
show_downloads: true
google_analytics:

# Theme data
markdown: kramdown
highlighter: rouge

# Gem plugins
plugins:
  - jekyll-seo-tag

# Demo site specific elements
baseurl: mixtape

# Use YAML lists like this to dynamically choose names 
# and relative/absolute links for the top-level links 
# and navigation bar in the site.

# For header links, the theme defaults to the following 
# schema.
# If they are not explicitly included, the correpsonding 
# buttons don't populate in builds, though they do 
# populate in deployments to GitHub Pages.
# -------
# github:
#   repository_url: https://github.com/my/repository
#   zip_url: https://github.com/my/repository/archive/branch.zip
#   tar_url: https://github.com/my/repository/archive/branch.tar.gz

# To customize header links, you need a list of items 
# which include a name (button text) and URL to the 
# resource.

# header_links:
#   - url: http://127.0.0.1:4000
#     name: View Site
#   - url: https://google.com
#     name: Google Search
#   - url: facebook.com
#     name: Facebook
#     Note that this is broken; the external protocol 
#     is missing.
#   - url: /
#     name: ET Go Home

# Likewise, navigation bar links can be customized and 
# given custom text. These links can be relative or 
# external.

# nav_links:
#   - url: /
#     name: Home
#   - url: /blog
#     name: Dev Log
#   - url: https://google.com
#     name: Learn
